service: MioChatBot

provider:
  name: aws
  runtime: python3.6
  profile: tutorial-profile

functions:
  handle_lookup:
    handler: handler.handle_lookup
    events:
      - http:
          path: lookup
          method: any
